steps:
  ###########################################################
  # Step 1: Retrieve the cached .m2 directory from GCS
  ###########################################################
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - 'gs://${_BUCKET}/cache/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
  ###########################################################
  # Step 2: Build, Test, and Verify
  ###########################################################
  - name: 'gcr.io/cloud-builders/mvn'
    args:
      - 'clean'
      - 'verify'
      - '--batch-mode'
    dir: '/workspace'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
  ###########################################################
  # Step 3: Update cached .m2 directory on GCS with any
  #         additional dependencies downloaded during the
  #         build.
  ###########################################################
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '/cache/.m2'
      - 'gs://${_BUCKET}/cache/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
  ###########################################################
  # Step 4: Build docker image
  ###########################################################
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker pull gcr.io/$PROJECT_ID/exchange:latest || exit 0' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t', 'gcr.io/$PROJECT_ID/exchange:$COMMIT_SHA',
           '--cache-from', 'gcr.io/$PROJECT_ID/exchange:latest',
           '.']
    dir: '/workspace'

images: ['gcr.io/$PROJECT_ID/exchange:$COMMIT_SHA']

substitutions:
  # Default values
  _BUCKET: 'gcloud-ozink-bucket1'